### ISSUE TITLE
Add WebPage entity to Message object

### ISSUE THREAD

**Issue by moelius** [pyrogram/pyrogram#104]
Hi, I can see photos, video, documents, etc entities in Message objects, but there is not WebPage parsed entities.
Can you add this feature? P.S. Example post with WebPage: https://t.me/DeCenter/3089

**Comment by moelius** [comment]
I think this is not urgent, since you can get this information manually using raw messages

**Comment by delivrance** [comment]
If I remember correctly, there's a little issue with WebPages: you don't always have them available at the time a message is sent because the server needs to fetch the URL and generate a photo/file, and if is not cached yet it will take a while (and of course the Telegram message can't wait for it). That's why we have [UpdateWebPage](https://docs.pyrogram.ml/types/UpdateWebPage). We need to experiment with this.

**Comment by zeroone2numeral2** [comment]
I have a Pyrogram bot that sends images contained in link previews as actual photo objects, it has been running for quite a lot now and I'm full of logs. Unfortunately I can't give an estimate of how many times Telegram, returns a `WebPagePending` without parsing my log file, but I can confirm it happens quite often and also, when the server is not able to serve a preview in a short time, it makes you usually wait for 120 seconds

**Comment by delivrance** [comment]
Just in case anyone else stumbles upon and decides to work on this, @mendelmaleh is currently implementing the feature.

**Comment by delivrance** [comment]
Feature added in #268
