### ISSUE TITLE
Lots of unnecessary calls for clients with many groups

### ISSUE THREAD

**Issue by xFeliXx** [pyrogram/pyrogram#1088]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version

### Description

I'm running a client with an account that has around 100 group chats with many frequent messages.
When I run a pretty much empty script with just a standard Pyrogram event loop and no update handlers, I constantly get the following warnings:
```text
[test] Waiting for 9 seconds before continuing (required by "channels.GetMessages")
[test] Waiting for 14 seconds before continuing (required by "channels.GetMessages")
[test] Waiting for 13 seconds before continuing (required by "channels.GetMessages")
[test] Waiting for 5 seconds before continuing (required by "channels.GetMessages")
[test] Waiting for 4 seconds before continuing (required by "channels.GetMessages"
```

In addition to that, when I'm doing a little bit more extensive load with a script (that also gets the messages from the groups by itself), I'm experiencing a loss of events and the "on_message" update handler is not being called for some of the messages.

It seems that on every received message that has the "reply_to" attribute, Pyrogram makes the `client.get_messages()` method call unless the original ("reply_to") message is cached: https://github.com/pyrogram/pyrogram/blob/8490cfa0a92e2d57b6de9728b1d18ee3071be5b4/pyrogram/types/messages_and_media/message.py#L820

Is there any smart way around this problem?

### Steps to reproduce

1. Use a Telegram account that is joined into many group chats (100+) with many frequent messages inside of them (at least 10 messages/second from all chats combined).
2. Execute the following example with a running event loop:
```python
from pyrogram import Client

app = Client("my_account")

app.run()
```
3. Wait a little bit for the warnings to appear in the console.

**Comment by delivrance** [comment]
There is no unnecessary call. All calls are useful for the library to properly work. In this case, the calls are useful to keep the `reply_to_message` field available for new incoming messages as intended.

The issue mentioned arises because the client is:
- receiving lots of messages that are replies to other messages, in particular to old messages which are not cached and therefore fetched automatically. There's nothing that can be done in this case as messages need to be known (all new incoming messages are cached automatically).
- reaching the cache size limit and therefore older messages are being discarded from the cache making the library fetch those discarded messages in case new messages reference them. You can try increasing the cache size with the following code (note that setting the cache size is currently not available straight from a Client parameter, so you need to manually import and set the attribute):
  ``` python
  from pyrogram.client import Cache
  
  app = Client("account")
  app.message_cache = Cache(1000000)

  ...
  ```

**Comment by delivrance** [comment]
What is probably happening is that, upon starting the client, new incoming messages are referencing old not-yet-known messages which are automatically fetched and which cause the warnings. As soon as enough messages are cached (i.e. enough time has passed) you should not see any warning anymore.

**Comment by xFeliXx** [comment]
@delivrance,

Thanks for the suggestion!

I've increased the cache size. From the looks of it it's gotten better, but I still experience some problems. Warnings still appear and some message events are not being received by the script. The problem with increasing the cache size is a high memory consumption, while the original problem is not being resolved completely.

I've also tried to keep the script running but that doesn't stop the warnings from appearing. Though it seems like they appear less frequently after some time.

Do you have any idea why some events can be lost? When I'm testing with an account that doesn't receive a lot of frequent messages then I don't experience such problems, so I think it's directly related to the flood wait timeouts from the Telegram.

Is there an option to completely omit some unneeded events from processing by the Pyrogram For example omit all message events from group chats, but still process all private chat events.

**Comment by xFeliXx** [comment]
I have removed parsers for the events which were causing the flood waits, as they were not needed for my specific use case.
And that seemed to help with the missing events issue, at least for now.

```python
from pyrogram import Client
from pyrogram.dispatcher import Dispatcher
from pyrogram.raw.types import UpdateNewChannelMessage, UpdateEditChannelMessage, UpdateDeleteChannelMessages

class CustomDispatcher(Dispatcher):
    def __init__(self, client: Client):
        super().__init__(client)

        self.update_parsers.pop(UpdateNewChannelMessage)
        self.update_parsers.pop(UpdateEditChannelMessage)
        self.update_parsers.pop(UpdateDeleteChannelMessages)

app = Client("my_account")
app.dispatcher = CustomDispatcher(app)

app.run()

**Comment by delivrance** [comment]
The missing events happening in very busy accounts are due to a currently unimplemented feature that would do exactly that: detect and fetch missing events because of gaps in server's pushes.

There's no way in the API to selectively exclude specific events from being received, you can at most not handle them (by simply not setting any event handler) or disable them altogether with `Client(..., no_updates=True)`.
