### ISSUE TITLE
__init__() got an unexpected keyword argument 'phone_number'

### ISSUE THREAD

**Issue by Padandish** [pyrogram/pyrogram#11]
Hi dears,

Error:
> Traceback (most recent call last):
>   File "C:/Users/KW/Desktop/Pyrogram/0001.py", line 15, in <module>
>     password="pass"
> TypeError: __init__() got an unexpected keyword argument 'phone_number'

Code:
```
from pyrogram import Client
from pyrogram.api.errors import (Error)

try:
    def phone_code_callback():
        code = input("Please input phone code: ")
        return code


    client = Client(
        session_name="0001",
        test_mode=False,
        phone_number="12111850539",
        phone_code=phone_code_callback,
        password="password"
    )

    client.start()

    print(client.get_me())

except Error:
    pass
```

**Comment by delivrance** [comment]
@Padandish Hi there! Please refer to: https://docs.pyrogram.ml/getting_started/QuickInstallation/#bleeding-edge

The version you install from PyPI (pip) might not be the latest, to get the most up to date development version use pip install --upgrade git+https://github.com/pyrogram/pyrogram.git. A new updated version will be pushed soon.

P.S. Maybe you want to join our group chat for asking such questions instead of opening a GitHub issue: [@PyrogramChat](https://t.me/PyrogramChat)

**Comment by Padandish** [comment]
Thanks

Python 3.6.0 |Anaconda 4.3.0 (64-bit)
pyrogram.__version__ '0.4.2'

Should be use beta versions?

Telegram said: "username @PyrogramChat not found."

**Comment by delivrance** [comment]
The version is still the same, but you are now running changes you find in the master branch, and your code above will work.

About the group, I'm not sure what you did, but [click here to join](https://t.me/PyrogramChat).
