### ISSUE TITLE
how to catch client.media_download(...)  error

### ISSUE THREAD

**Issue by huzhamiao** [pyrogram/pyrogram#1130]
### Checklist

- [X] I believe the idea is awesome and would benefit the framework
- [X] I have searched in the issue tracker for similar requests, including closed ones

### 1、can't catch the pyrogram.errors.exceptions.bad_request_400.FileReferenceExpired by using follow code:

```
try:
    await client.download_media(message)
except Exception as e:
    print(e)
```
### 2、When debug into pyrogarm source code,found code is 

```

  try:
            r = await session.invoke(
                raw.functions.upload.GetFile(
                    location=location,
                    offset=offset_bytes,
                    limit=chunk_size
                ),
                sleep_threshold=30
            ) 
...
...

 except Exception as e:
            log.error(e, exc_info=True)
```

### 3、why 
This can help to kown which success when use ayncio.gather,and record the message download status in mysql

**Comment by delivrance** [comment]
`download_media` will return `None` in case of failures. See https://docs.pyrogram.org/api/methods/download_media for more.

**Comment by bitjerry** [comment]
> `download_media` will return `None` in case of failures. See https://docs.pyrogram.org/api/methods/download_media for more.

It is better to throw the error instead of swallowing this error. In the user code, we only know that the download failed, but cannot determine why. For example, in my code, the download times out, and I want to prompt the user about the problem.
![image](https://github.com/pyrogram/pyrogram/assets/52879142/773ed621-f6eb-470e-9006-813cd6181d8b)
![image](https://github.com/pyrogram/pyrogram/assets/52879142/e65dd24b-f923-4405-9570-7c23192c606b)
