### ISSUE TITLE
Questions:  chat URL

### ISSUE THREAD

**Issue by sebawolf** [pyrogram/pyrogram#131]
Hi!

I'm new to this (I started using your python library a couple of days ago) and I'd like to know how to build the chat URL based on the "alias" string (chat.username)...

For example, using your "get_chat" function (id = -1001299159555), I get a chat object with this attribute (among others): chat.username = youtube_trend

I know I can build an URL based on that "alias" ("https://telegram.me/ALIAS"), in this case: https://telegram.me/youtube_trend

...but I found many chats with no alias, for example chat id = -1001146297748. How can I build the chat url in this case?

----------

Another URL example would be (telegram web client chat url):
https://web.telegram.org/#/im?p=@youtube_trend

For the other chat (with no alias), according to my web client, I know its url is:
https://web.telegram.org/#/im?p=s1146297748_13856039024240927706

But I don't know what's the second part of that id (the "13856039024240927706" part of that string).

----------

I hope you could help me...

Thanks!

**Comment by zeroone2numeral2** [comment]
> ...but I found many chats with no alias, for example chat id = -1001146297748. How can I build the chat url in this case?

You can't. There is not chat url for private groups or channels, because they are, well, not public. Only public chats (chats with an username) have a public, human-readable and everlasting url.

> For the other chat (with no alias), according to my web client, I know its url is:
https://web.telegram.org/#/im?p=s1146297748_13856039024240927706

I honestly don't know what that `p` parameter stands for, but is something specific to Telegram Web and I'm pretty sure it's different for every member of that chat (that's not a direct link to the chat)

Anyway, if your account is administrator in the chat and has the permission to invite new members, you can use the [`client.export_chat_invite_link()`](https://docs.pyrogram.ml/pyrogram/Client#pyrogram.Client.export_chat_invite_link) function to generate an invite link which can be shared around the web and can be used by anyone to _join_ the group/channel

**Comment by delivrance** [comment]
@zeroone2numeral2 is right, chat links like https://web.telegram.org/#/im?p=s1146297748_13856039024240927706 are only valid for you and specific to webogram.

> But I don't know what's the second part of that id (the "13856039024240927706" part of that string).

Here's the technical explanation: the way Telegram works makes it impossible to access chats with the id only (except for basic groups) in order to prevent automated scraping tools. A pair of id/access_hash is used instead: the id (1146297748, `s` prefix to denote that is a channel/supergroup; Pyrogram uses `-100` like the bot api) never changes and the access_hash (13856039024240927706, generated by the server just for you) is different for each user and session.
