### ISSUE TITLE
High CPU usage 

### ISSUE THREAD

**Issue by i-paya** [pyrogram/pyrogram#165]
Hi .
I was using Pyrogram version 0.6.2 on my Ubuntu server and the CPU usage was ok .
Now i'm using the same codes and the same version of pyrogram on another Ubuntu server and CPU usage is extremely high .
Is there any way I can  reduce the CPU usage  ?

I can't access to the old Ubuntu server and I don't know the installed packages.

**Comment by delivrance** [comment]
@i-paya v0.6.2 is pretty old (more than 8 months old), I suggest you to update to the latest version first.

I can't know what's causing this without any details, but Telegram crypto could be quite heavy in case of busy accounts. You have to give me a way to reproduce the issue.
Also make sure you install TgCrypto because the default AES implementation is written in Python and is massively slower.

**Comment by i-paya** [comment]
If I update to the last version I have to write my code again .
I have installed TgCrypto .

**Comment by delivrance** [comment]
@i-paya I'm not supporting old versions because if it turns out to be a bug it's probably fixed already and the only way to confirm this is by sending a minimal example that reproduces the issue so we can try on both versions.

**Comment by i-paya** [comment]
I know that's not a bug .

Maybe something is wrong with my Ubuntu server 😄 or some packages .
I tested echo bot example , but I have the same problem .
I don't know why my old Ubuntu server was so good .
