### ISSUE TITLE
AttributeError: No API Key found

### ISSUE THREAD

**Issue by zachyam** [pyrogram/pyrogram#176]
```
Traceback (most recent call last):
  File "server.py", line 11, in <module>
    app.run()
  File "/usr/local/lib/python3.7/site-packages/pyrogram/client/client.py", line 367, in run
    self.start()
  File "/usr/local/lib/python3.7/site-packages/pyrogram/client/client.py", line 230, in start
    self.load_config()
  File "/usr/local/lib/python3.7/site-packages/pyrogram/client/client.py", line 932, in load_config
    "No API Key found. "
AttributeError: No API Key found. More info: https://docs.pyrogram.ml/start/ProjectSetup#configuration
```

I get the above error when I run the following code:

```
app = Client("7229XXXXX:XXXXXz-poz-qGC-8pqdMO5-ORRA84yXXXXX")
app.start()
app.send_message("me", "Hi there! I'm using **Pyrogram**")

```

The parameter I pass into Client is the bot token obtained when creating a new bot using BotFather.
Any suggestions on how to debug or what the issue is?

**Comment by delivrance** [comment]
![image](https://user-images.githubusercontent.com/14043624/50055781-97128f00-0153-11e9-8cc4-e07c144b3f05.png)

**Comment by delivrance** [comment]
Also read #173

**Comment by foorman** [comment]
Try to run pyrogram script, get error:
**The api_id/api_hash combination is invalid**

![изображение](https://user-images.githubusercontent.com/888379/70388790-4fad9000-19ae-11ea-9c3a-43cc7d371378.png)


What am I entering not correct? 
![изображение](https://user-images.githubusercontent.com/888379/70388752-df067380-19ad-11ea-9e32-4f957c10816e.png)

**Comment by foorman** [comment]
Throws error after a while [Win 10065]
Which port pyrogram uses and how to open it?
Thanks

_[https://help.globalscape.com/help/archive/cuteftp6/socket_errors_10060,_10061,_10064,_10065.htm]
Socket errors 10060, 10061, 10064, 10065

An socket error the 10060 range is a Winsock error generally caused by either outgoing connection problems or connection problems on the host end.

for error WSAESERVERUNREACH (10065)

The server is unreachable. Verify that the destination host name or IP address is correct and try again later._

**Comment by ColinTheShark** [comment]
First of all: This Issue is almost a year old. Just open a new one.

Secondly: To connect to the MTProto API with Pyrogram you require the `api_id` and `api_hash` from my.telegram.org. The Bot Token you passed is not enough to connect correctly and is a replacement for your phone number when connecting as a BOT instead of a USER.

I suggest you head over to the documentation and read carefully as for what to do. https://docs.pyrogram.org/intro/setup

----- 

As for the other error in your second comment: I have no idea what causes that. I haven't set up any firewall exceptions and it works from my machine.

**Comment by foorman** [comment]
I thought I tried all available ways, but tried **api_id and api_hash from my.telegram.org** again and it worked

Thanks man

**Comment by elizavetaanisimova** [comment]
404 https://docs.pyrogram.org/intro/setup

**Comment by MatveyPRO3** [comment]
https://docs.pyrogram.org/start/auth#bot-authorization
