### ISSUE TITLE
reply_to_msg_id and reply_to_message_id

### ISSUE THREAD

**Issue by RadRussianRus** [pyrogram/pyrogram#276]
There are 21 code search results for `reply_to_msg_id` and 22 for `reply_to_message_id`. Why there are two separate names for this? It's kinda annoying, since you can mistake one for another easliy.

I'm proposing to change existing `reply_to_message_id` to `reply_to_msg_id`, since latter is used in TL-scheme, so there won't be any differences.

**Comment by RadRussianRus** [comment]
Oh, didn't knew that it adds labels based on template.
Is it better to republish it? :thinking: 
It's more like naming issue than bug, I think.

**Comment by delivrance** [comment]
> Is it better to republish it? 🤔

It's ok, don't worry

> There are 21 code search results for...

`reply_to_message_id` is being used by the bot API as well as everywhere in pyrogram's API, unless I mistyped somewhere.. Can you tell me exactly where's the issue? Searching for `reply_to_msg_id` only reveals usages from the raw API, which is ok.

**Comment by RadRussianRus** [comment]
Well, the problem arises when you start mixing raw API with Pyrogram's API. For example, I'm using raw API for drafts, because for now there is only raw API for this. And I've noticed that I often mistype one with another. I understand that it's used in Bot API, so complete change is not acceptable. But maybe some aliases then?

**Comment by delivrance** [comment]
Adding extra arguments just to alias some existing ones is a big no. Not only it pollutes the API by introducing unnecessary confusion, but it also makes it harder to maintain the code because it has to check on every applicable method which parameter was filled in.

Having said that, You IDE should be able to warn you in case you are passing a wrong keyword argument. Currently, no method in both raw API and Pyrogram's API allow extra **kwargs, so you either get a warning in your IDE or Python will surely complain at runtime with an `unexpected keyword argument` error.

**Comment by RadRussianRus** [comment]
Alright, thanks.
