### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters in position 1535-1542: ordinal not in range(128)

### ISSUE THREAD

**Issue by itsecres-nandant** [pyrogram/pyrogram#357]
## Checklist
- [x] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.
- [x] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/develop.zip` and reproduced the issue using the latest development version.

## Description
UnicodeEncodeError: 'ascii' codec can't encode characters in position 1535-1542: ordinal not in range(128)

## Steps to Reproduce
from pyrogram import Client

api_id = 123456
api_hash = "0644dd76d7855e139941106b9f61e325"

with Client("abcdefg", api_id, api_hash) as app:
    print(app.get_history("pyrogramchat"))

## Traceback
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    print(app.get_history("pyrogramchat"))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 1535-1542: ordinal not in range(128)

**Comment by delivrance** [comment]
@itsecres-nandant 

1. Format your code and make it look nicer.
2. The steps that reproduce the issue are not good since `get_history` results may vary in time. You have to provide a reproducible example (if something is failing there it's likely because of a single message, find exactly that message).
3. Your terminal is probably forcing python in ascii mode, you have to fix that in your terminal settings.
