### ISSUE TITLE
Add support for older layer Objects

### ISSUE THREAD

**Issue by 4l1fe** [pyrogram/pyrogram#43]
Now i examine the library functionality and have a need to store some objects in a DB.
So they are not similar and i wanna just dump them to bytes to store as is for further using.

For example:
```
pyrogram.api.types.contact.Contact
pyrogram.api.types.user.User
pyrogram.api.types.chat_forbidden.ChatForbidden
pyrogram.api.types.dialog.Dialog
```

Are there any pitfalls?

**Comment by delivrance** [comment]
Weird use case, but yeah is surely possible. Any Pyrogram Object (both types and functions) can be serialized using the `.write()` method. You get a bytes string which can be loaded again using `Object.read(b)` (`b` must be a BytesIO object), from `pyrogram.api.core.Object`.

The only downside would be versioning. New layer updates could modify the types/functions schema and you won't be able to load old objects with the updated library. This can be handled by saving the layer number as well in your DB, but Pyrogram currently lacks support for older layers.

**Comment by delivrance** [comment]
All the latest [functions](https://docs.pyrogram.ml/functions/) and [types](https://docs.pyrogram.ml/types/) are coming straight from the official Telegram clients schema, but they aren't documented at all. Fortunately, the names are descriptive enough to get an idea of what they do.

Anyway, it turns out that this approach is actually used by the official Android app: it saves raw messages plus the layer number and loads them again when needed using the correct schema.

I'll flag this as enhancement. Maybe we could add support for old layers someday, but for now this is a low priority. Thanks for the suggestion ^^

**Comment by delivrance** [comment]
This is unlikely to happen. Closing for now.
