### ISSUE TITLE
No docs about finishing idle() properly

### ISSUE THREAD

**Issue by LeonardoRick** [pyrogram/pyrogram#492]
I was reading idle() docs and I had a doubt on this: 

> calling idle() will ensure the client(s) will be kept alive by not letting the main script to end, until you decide to quit

How can I programaticaly decide to quit? I don't want to press Ctrl+C because based in some conditions my program need to be finished, and tg.stop() do not stop idle(). Is that possible?

**Comment by delivrance** [comment]
Ctrl+C is just one way to send a signal to the process, you can do that programmatically as well (search how to send signals to the own process in python). Anyway, this is a weird usage because you are running an event driven application that's supposed to be kept up indefinitely, until – from the outside – you decide to stop it. Alternatively, replace idle() with anything that does not end the main script and doesn't block the main thread while listening for your condition to be set.
