### ISSUE TITLE
 asynchronous scalability & overall performance

### ISSUE THREAD

**Issue by tiniumv** [pyrogram/pyrogram#541]
I am interested in pyrogram as high-performance, asynchonous library. 
During my research, i ran into some performance issues.
Folowing code was used as a benchmark:

```
async def pyrogram_worker(app, channel):
    from pyrogram.raw import functions
    await app.send(functions.messages.GetHistory(
        peer=await app.resolve_peer('telegram'),
        limit=20,
        offset_date=int(datetime.now().timestamp()),
        offset_id=0,
        max_id=0,
        min_id=0,
        add_offset=0,
        hash=0
    ))

async def poc_pyrogram(coroutines_number):
    async with Client(
        'client',
    ) as app:
        start_time = time.time()
        await asyncio.gather(*[
            pyrogram_worker(app, 'telegram')
            for i in range(coroutines_number)
        ])
        end_time = time.time()

    print(end_time-start_time)

if __name__ == '__main__':
    asyncio.run(poc_pyrogram(1))
```

* I have found that json encoding takes significant (~50% - see screenshot) amount of code execution's time. This proportion is sustainable relatively to "limit" parameter of GetHistory function.
Have there been any plans for replacement standard json with something more efficient?
In case below, single coroutine with GetHistory used 4.448 seconds to complete:
![bad_json](https://user-images.githubusercontent.com/1054043/99455768-5b813080-2939-11eb-9ecd-7ca4d3cc4853.png)

* Moreover, I noticed that launching GetHistory in separated coroutines does not help to speed up requesting data. I was raising "coroutines_number" arg of poc_pyrogram function, and time to complete was raising much faster than i hoped.
 ```
 |n = 3   |n = 9  |n = 15  |
 |t = 3.28|t = 8.50|t = 12.5|
 ```

Again, have this evere came under someone's attention? Is there an comprehensible way to do something with it?

Thanks.

**Comment by Nizarius** [comment]
The same results for me. Pyrogram positions itself as a performance library, but its speed is much lower than Telethon's one. 

Can we fix the bottlenecks described above?

**Comment by delivrance** [comment]
@tiniumv Thanks for pointing this out, but I am really unable to see such slowdowns on my side using your example; the snippet on my machine completes in less than half a second. I confirm however that, for some reason, json is being invoked way too many times and this seems like a bug to me since json is never used anywhere unless you are going to print() or str() objects. While I investigate more on this, you could try to repeat your tests with these two lines commented out and let me know if that helps: https://github.com/pyrogram/pyrogram/blob/e4405db50dc5c247e1fef0e3440e02c8ff4903a7/pyrogram/raw/core/tl_object.py#L52-L53

@Nizarius while using raw methods alone can be a way to tell raw performance differences between libraries, this can't hold for high level methods which, as the name suggests, are implemented in such a way to be convenient and friendly. For instance, the raw method GetHistory doesn't return the replied-to-messages of the obtained messages, whereas get_history (the friendlier method) does, and that translates to extra network calls made for API consistency and convenience.

**Comment by delivrance** [comment]
The JSON decoding issue taking a lot of CPU resources has been solved.
