### ISSUE TITLE
app.start() doens't work like ealier

### ISSUE THREAD

**Issue by petripanula** [pyrogram/pyrogram#545]
app.start() doesn't work lke it worked earlier... Here I'm not able ti run my code any more at the same time than Pyrogram.. Using app.run() blocks the code and app.start() doesn't show any messeages sent in Telegram..

Python version 3.7.9
Pyrogram v1.0.7

```python
import threading
import time
import sys
from pyrogram import Client
from pyrogram import idle

app = Client("my_account")

@app.on_message()
async def my_handler(client, message):
    print(message)
    #await message.reply_text("Hello, async world!")


print("Python version")
print (sys.version)

#app.run()   # <--- This blocks...
app.start()  # <--- This doesn't show anything in my_handler
#idle()    # <--- Adding this after app.start() blocks again...


print("Going to while loop...")

# While loop
i = 0
while(True):
    print("looping...")
    time.sleep(2)
    i = i + 1
    if i > 5:
        break

```

**Comment by delivrance** [comment]
This is not an issue and `idle()` blocks as intended (read the docs). You are supposed to code your applications asynchronously because Pyrogram is an async library. Infinite/long loops or anything else that blocks the main thread will also block python's internal event loop which Pyrogram is relying on.

If you want such loops you have to use asyncio tasks to have them run concurrently.
