### ISSUE TITLE
PhoneCodeExpired The confirmation code has expired (caused by "auth.SignIn")

### ISSUE THREAD

**Issue by and3h** [pyrogram/pyrogram#584]
first I get the code and hash code using the req_code method
Then I pass the number and 5-digit code and hash code to the submit method

But I got this error

pyrogram.errors.exceptions.bad_request_400.PhoneCodeExpired: [400 PHONE_CODE_EXPIRED]: The confirmation code has expired (caused by "auth.SignIn")

also this my code

```
from pyrogram import errors, Client

class Authorization:
    def __init__(self, number):
        self.number = number
        self.api_id = 123456
        self.api_hash = 'XXXXXXXXXXXXXXXXXXXXXX'
        
    def req_code(self):
        app = Client(
                self.number ,
                api_id=self.api_id,
                api_hash=self.api_hash,
            )
        try:
            app.connect()
            app.send_message('me', 'this is a simple test')
        except errors.Unauthorized:
            code = app.send_code(self.number)
            print(code.phone_code_hash)
            app.disconnect()
            return f'The Code Soccessfully Sent for {self.number} and hash is {code.phone_code_hash} Please Save hash.'

        except errors.UserDeactivated:
            app.disconnect()
            return 'The user has been deleted/deactivated'
        except errors.UserDeactivatedBan:
            app.disconnect()
            return 'This Number Is Ban'
        except errors.ApiIdInvalid:
            app.disconnect()
            return 'The key is invalid'
        except:
            return 'Unknown Error'
    def submit(self, code, phone_code_hash, paswd):
        app = Client(
                self.number ,
                api_id=self.api_id,
                api_hash=self.api_hash,

            )
        app.connect()
        try:
            print(1)
            app.sign_in(phone_number =self.number,phone_code=code ,phone_code_hash=phone_code_hash )
            print('soccess')
        except errors.SessionPasswordNeeded:
            print(2)
            app.password = paswd
            #app.check_password(password=paswd)
            app.sign_in(phone_number=self.number, phone_code=code, phone_code_hash=phone_code_hash)
            
            print('Success Login With Password')


if __name__ == '__main__':
   '''  fisrt request  5-digit code   by req_code() sec submit() request to sing in '''
    obj = Authorization('+11111111')
    obj.req_code()
    #Authorization('+111111111').submit(code='12345',phone_code_hash='4fd9fcc37ea119abfa',paswd='123456789') 


```

 ```
 File "C:\Users\python\Desktop\pytrogram.py", line 45, in submit
    app.sign_in(phone_number =self.number,phone_code=code ,phone_code_hash=phone_code_hash )
  File "C:\Program Files\Python38\lib\site-packages\pyrogram\sync.py", line 56, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Program Files\Python38\lib\site-packages\pyrogram\methods\auth\sign_in.py", line 61, in sign_in
    r = await self.send(
  File "C:\Program Files\Python38\lib\site-packages\pyrogram\methods\advanced\send.py", line 77, in send
    r = await self.session.send(
  File "C:\Program Files\Python38\lib\site-packages\pyrogram\session\session.py", line 441, in send
    return await self._send(data, timeout=timeout)
  File "C:\Program Files\Python38\lib\site-packages\pyrogram\session\session.py", line 411, in _send
    RPCError.raise_it(result, type(data))
  File "C:\Program Files\Python38\lib\site-packages\pyrogram\errors\rpc_error.py", line 78, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.PhoneCodeExpired: [400 PHONE_CODE_EXPIRED]: The confirmation code has expired (caused by "auth.SignIn")
```

**Comment by delivrance** [comment]
Either it simply expired because you took too long or https://docs.pyrogram.org/faq?highlight=faq#my-verification-code-expires-immediately.

**Comment by adolfaka** [comment]
This exception is not raised for this reason, pay attention to this part of the code:

https://github.com/pyrogram/pyrogram/blob/0b0bec9e278ee29ed6e84f4237cc9c39cc8ce55c/pyrogram/methods/auth/connect.py#L39

https://github.com/pyrogram/pyrogram/blob/0b0bec9e278ee29ed6e84f4237cc9c39cc8ce55c/pyrogram/client.py#L671-L690


Since the **user_id** and **bot_is** values are None, then we get a new **auth_key** which is not the same as **phone_code_hash**

Decision:

```
sed -i 's/await self.storage.user_id() is None,/# await self.storage.user_id() is None,/g' /usr/local/lib/python3.7/site-packages/pyrogram/client/client.py 
sed -i 's/await self.storage.is_bot() is None/# await self.storage.is_bot() is None/g' /usr/local/lib/python3.7/site-packages/pyrogram/client/client.py
```

**Comment by parikls** [comment]
@delivrance why this issue was closed? It's not the case when you share the telegram code via the client - see the comment of @adolfaka above. The library itself is updating the AuthKey for no reasons. Therefore the library becomes "stateful" until you log in. Here is the small "reproducible" piece which will lead to the `PHONE_CODE_EXPIRED` error.

```
phone_number = ...
client = Client(...)
await client.connect()
sent_code = await client.send_code(phone_number)
await client.disconnect()
await client.connect()
await client.sign_in(phone_number, sent_code.phone_code_hash, phone_code)
```


And to be able to avoid this - you need to almost fully copy the `client.connect` method

**Comment by delivrance** [comment]
> The library itself is updating the AuthKey for no reasons.

@parikls the reason is manually disconnecting and reconnecting again in the middle of the login. Doing so will restarts the login flow as it needs to be completed within the same connection.

> Since the user_id and bot_is values are None, then we get a new auth_key which is not the same as phone_code_hash

@adolfaka not sure what you mean, that part of the code has nothing to do with the phone code. the auth key and the phone code hash are two different things as well.

**Comment by parikls** [comment]
@delivrance 

> the reason is manually disconnecting and reconnecting again in the middle of the login. Doing so will restart the login flow as it needs to be completed within the same connection.

But it shouldn't. If the auth key will be the same - you can login even with the disconnecting in the middle. This doesn't happen not in official web client nor in telethon because they keep the same auth key. In the web applications it's a common case that first request will get the code, while the following request will send the received code. 

Here is the proof that it will work even if i disconnect the client after sending the code. That's actually the copied `connect` method but without loading the session to avoid changing the auth key:

```
client = Client(...)

client.load_config()
client.session = Session(
    client,
    await client.storage.dc_id(),
    await client.storage.auth_key(),
    await client.storage.test_mode()
)
await client.session.start()
client.is_connected = True
```

> not sure what you mean, that part of the code has nothing to do with the phone code. The auth key and the phone code hash are two different things as well.

That's not true. If the auth key will be different - login with the received code will fail with `PHONE_CODE_EXPIRED`

**Comment by parikls** [comment]
@delivrance does this makes sense? I've also searched over the Pyrogram tg chats and this issue actually appeared many times for many people. I believe the issue should be re-opened. Or i can create a separate one with the detailed description.
