### ISSUE TITLE
Sleeping for 26s (required by "messages.GetDialogs")

### ISSUE THREAD

**Issue by am11y** [pyrogram/pyrogram#749]
## Checklist
- [x] I am sure the error is coming from Pyrogram's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.
- [x] I ran `pip3 install -U https://github.com/pyrogram/pyrogram/archive/master.zip` and reproduced the issue using the latest development version.

## Description
When iterating through dialogs using the code below, I gett constant "sleeping for X seconds) message. This code worked without problems until today. Did Telegram change something in their API? This problem does not come up if I use telethon library.

``` python
client = Client( session_name = "test",
                 api_id = keys["api_id"],
                 api_hash = keys["api_hash"]
                 )

client.start()

for dialog in client.iter_dialogs():
    print( dialog.chat.title )`
...
```

**Comment by holnburger** [comment]
PR created to fix this, see: https://github.com/pyrogram/pyrogram/pull/750

**Comment by jonatan1609** [comment]
> PR created to fix this, see: https://github.com/pyrogram/pyrogram/pull/750


As I commented there, that PR does nothing but ignoring dialogs (in case there is only 1).
The reason it worked for you is because your account was not floodwait-ed. so you thought that's fixing that. Personally, i think that the issue owner was having floodwait because he did a lot of stuff at the same time/very short sleeps between each action, and that's why he encountered a floodwait from this rpc call.

**Comment by holnburger** [comment]
> > PR created to fix this, see: #750
> 
> The reason it worked for you is because your account was not floodwait-ed. so you thought that's fixing that. 

I had the same issue as @am11y with all my accounts using iter_dialogs(). I expect that before yesterday using the offset date of the last dialog didn’t return any dialogs – now it does: it returns the last dialog. 

iter_dialogs() is iterating until it doesn’t see any more dialogs, so it’s continuing in an endless loop and reports rate limit awaits. 

`if not dialogs: ` therefor isn’t working right now. 
You could also check if the offset_date has the same value as in the loop before and then stop iterating.

**Comment by jonatan1609** [comment]
> > > PR created to fix this, see: #750
> 
> > 
> 
> > The reason it worked for you is because your account was not floodwait-ed. so you thought that's fixing that. 
> 
> 
> 
> I had the same issue as @am11y with all my accounts using iter_dialogs(). I expect that before yesterday using the offset date of the last dialog didn’t return any dialogs – now it does: it returns the last dialog. 
> 
> 
> 
> iter_dialogs() is iterating until it doesn’t see any more dialogs, so it’s continuing in an endless loop and reports rate limit awaits. 
> 
> 
> 
> `if not dialogs: ` therefor isn’t working right now. 
> 
> You could also check if the offset_date has the same value as in the loop before and then stop iterating. 
> 
> 
> 
> 
> 
> 

Oh, is it new that they return one dialog always? What if I don't have any dialogs yet?

**Comment by holnburger** [comment]
Checking with the current version and debugging via print:

```
        while True:
            dialogs = await self.get_dialogs(
                offset_date=offset_date,
                limit=limit
            )
            
            print(len(dialogs))
            
            if if not dialogs:
                return

            offset_date = dialogs[-1].top_message.date

            for dialog in dialogs:
                yield dialog

                current += 1

                if current >= total:
                    return
````

Script:

```
import pyrogram

app = pyrogram.Client("my_account", api_id, api_hash)

with app:
    for dialog in app.iter_dialogs():
        print(dialog.chat.title)
```

returns: 

```
Pyrogram v1.2.9, Copyright (C) 2017-2021 Dan <https://github.com/delivrance>
Licensed under the terms of the GNU Lesser General Public License v3 or later (LGPLv3+)

100
89
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
[my_account] Sleeping for 29s (required by "messages.GetDialogs")
```

With 189 dialogs in total. It continues to loop as dialog as `if not dialogs` will never be true. I tried it with `offset_date = dialogs[-1].top_message.date+1` to return zero dialogs (because there shouldn't be any dialogs after the last dialog) but it keeps returning the last dialog.

With

```
            if offset_date == dialogs[-1].top_message.date:
                return
````

Instead of 

```
            if not dialogs:
                return

```

the script is successfully running:

```
Pyrogram v1.2.9, Copyright (C) 2017-2021 Dan <https://github.com/delivrance>
Licensed under the terms of the GNU Lesser General Public License v3 or later (LGPLv3+)

100
89
1
RETURNS ALL CHAT TITLES
````


We are checking if the offset date changed since the last iteration and if it didn't we stop the loop. That's the better solution to my first hotfix (as my hotfix would skip the last dialog if there's 101, 201, ... total dialogs.

**Comment by delivrance** [comment]
This issue should be now fixed with latest changes.
