### ISSUE TITLE
Update on deleted message

### ISSUE THREAD

**Issue by mateusc-ciandt** [pyrogram/pyrogram#88]
Is there a way to receive an update event when a channel message is deleted?

Using the following code I get new messages and edited messages, but when a message is deleted, it does not trigger my method:
```python
@app.on_message(Filters.channel)
def from_channel(client, message):
    print(message)
```

**Comment by delivrance** [comment]
Hi! For completeness I'll answer here too, although the discussion started and is ongoing in the [official group chat](https://t.me/pyrogramchat). ^^

There's no way at the moment other than using `on_raw_update` (aka `RawUpdateHandler`) and manually filtering the updates.

The current idea is to add a whole new handler, namely `DeleteMessagesHandler`, and its decorator `on_deleted_messages` which will register a function with a **list of messages** (maybe [Messages](https://docs.pyrogram.ml/pyrogram/types/Messages)?) in its arguments instead of a **single Message**. This is preferred due to the fact that people can delete up to 100 messages at once and Telegram returns a single update containing the list of the deleted message ids; having something like `on_message(Filters.deleted)` is cool, but the callback function would be called up to 100 times for a single delete Update in order not to break the function signature and its consistency.

**Comment by mateusc-ciandt** [comment]
Hi @delivrance 
I totally agree with you, I'm working on the implementation of this handler. 

I will soon open the pull request! :smiley:

**Comment by mateusc-ciandt** [comment]
Like I said, I'm new to the python world. Feel free to give feedback on my Pull Request @delivrance :smile: 

Thanks

**Comment by vitalibr** [comment]
Like I said, I'm new to the python world. Feel free to give feedback on my Pull Request @delivrance smile

Thanks

**Comment by tahayasin2** [comment]
need just delete message
